---
name: DBIx-Encoding
version: v0.0.1
author:
  - 'Tatsuro Hisamori <medianetworks@gmail.com>'
abstract: Doing endoce/decode in the character code which you appointed in an attribute.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBI: 0
  Test::More: 0
  version: 0
configure_requires:
  Module::Build: 0.34
provides:
  DBIx::Encoding:
    file: lib/DBIx/Encoding.pm
    version: v0.0.1
  DBIx::Encoding::db:
    file: lib/DBIx/Encoding.pm
  DBIx::Encoding::st:
    file: lib/DBIx/Encoding.pm
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
